version: '3.3'

services:
  web:
    build: ./project
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - ./project/:/usr/src/project/
    ports:
      - 8080:8080
    env_file:
      - ./.env.dev